In [1]:
import numpy as np

#### 数组统计方法，既可以直接调用数组实例的方法，也可以使用顶层的Numpy函数。

In [2]:
arr = np.array([[1, 5, 3],[4, 2, 6]])
arr

array([[1, 5, 3],
       [4, 2, 6]])

In [3]:
# 调用数组实例的方法
arr.sum()

21

In [4]:
arr.mean()

3.5

In [5]:
# 使用顶层的Numpy函数
np.sum(arr)

21

In [6]:
np.mean(arr)

3.5

#### 指定axis参数，用于计算指定轴上的统计值

In [7]:
# axis=0——对a的横轴（行）进行操作，在运算的过程中其运算的方向表现为纵向（列）运算
arr.sum(axis=0)

array([5, 7, 9])

In [8]:
# axis=1——对a的纵轴（列）进行操作，在运算的过程中其运算的方向表现为横向（行）运算
arr.sum(axis=1)

array([ 9, 12])

In [9]:
# 计算标准差
arr.std(axis=0)

array([1.5, 1.5, 1.5])

In [10]:
# 计算方差
arr.var(axis=1)

array([2.66666667, 2.66666667])

In [11]:
# 计算最小值
arr.min(axis=0)

array([1, 2, 3])

In [12]:
# 计算最大值
arr.max(axis=1)

array([5, 6])

In [13]:
# 计算最小值的位置
arr.argmin(axis=0)

array([0, 1, 0], dtype=int64)

In [14]:
# 计算最大值的位置
arr.argmax(axis=1)

array([1, 2], dtype=int64)

#### cumsum和cumprod方法并不会对数据进行聚合，而是产生一个中间结果

In [15]:
# 元素累积和
arr.cumsum()

array([ 1,  6,  9, 13, 15, 21], dtype=int32)

In [16]:
arr.cumsum(axis=0)

array([[1, 5, 3],
       [5, 7, 9]], dtype=int32)

In [17]:
# 元素累积积
arr.cumprod()

array([  1,   5,  15,  60, 120, 720], dtype=int32)

In [18]:
arr.cumprod(axis=1)

array([[ 1,  5, 15],
       [ 4,  8, 48]], dtype=int32)