In [1]:
import numpy as np

# 1.唯一值：

In [2]:
np.unique([1, 1, 2, 2, 3, 3])

array([1, 2, 3])

In [3]:
arr = np.array([[1,1,3], [2,3,2]])
arr

array([[1, 1, 3],
       [2, 3, 2]])

In [4]:
np.unique(arr)

array([1, 2, 3])

#### 返回一个二维数组的唯一行

In [5]:
arr_2d = np.array([[1, 2, 3], [1, 2, 3], [3, 4, 5]])
arr_2d

array([[1, 2, 3],
       [1, 2, 3],
       [3, 4, 5]])

In [6]:
np.unique(arr_2d ,axis=0)

array([[1, 2, 3],
       [3, 4, 5]])

#### 返回唯一值在输入数组中的索引

In [7]:
arr = np.array([[1, 2, 3], [1, 2, 3], [3, 4, 5]])
arr

array([[1, 2, 3],
       [1, 2, 3],
       [3, 4, 5]])

In [8]:
np.unique(arr, return_index=True)

(array([1, 2, 3, 4, 5]), array([0, 1, 2, 7, 8], dtype=int64))

#### 根据唯一的值的索引重构输入数组

In [9]:
arr = np.array([[1, 2, 3], [1, 2, 3], [3, 4, 5]])
arr

array([[1, 2, 3],
       [1, 2, 3],
       [3, 4, 5]])

In [10]:
np.unique(arr, return_inverse=True)

(array([1, 2, 3, 4, 5]), array([0, 1, 2, 0, 1, 2, 2, 3, 4], dtype=int64))

#### 计算每个唯一值在输入数组中出现的次数

In [11]:
arr = np.array([[1, 2, 3], [1, 2, 3], [3, 4, 5]])
arr

array([[1, 2, 3],
       [1, 2, 3],
       [3, 4, 5]])

In [12]:
np.unique(arr, return_counts=True)

(array([1, 2, 3, 4, 5]), array([2, 2, 3, 1, 1], dtype=int64))

# 2.其他集合逻辑：

#### 计算x和y的交集、差集、并集、异或集

In [13]:
# 计算x和y的交集，并排序
np.intersect1d([1, 3, 4, 3], [3, 1, 2, 1])

array([1, 3])

In [14]:
# 计算x和y的并集，并排序
np.union1d([1, 3, 4, 3], [3, 1, 2, 1])

array([1, 2, 3, 4])

In [15]:
# 计算x和y的差集，在x中但是不在y中的元素
np.setdiff1d([1, 3, 4, 3], [3, 1, 2, 1])

array([4])

In [16]:
# 计算x和y的异或集，在x或y中，但是不属于x和y交集的元素
np.setxor1d([1, 3, 4, 3], [3, 1, 2, 1])

array([2, 4])

#### 如果需要计算两个以上数组的交集和并集需要使用Python中的Functools模块

In [17]:
from functools import reduce

In [18]:
# 计算x、y、z的交集
reduce(np.intersect1d , ([1, 3, 4, 3], [3, 1, 2, 1], [6, 3, 4, 2]))

array([3])

In [19]:
# 计算x、y、z的并集
reduce(np.union1d , ([1, 3, 4, 3], [3, 1, 2, 1], [6, 3, 4, 2]))

array([1, 2, 3, 4, 6])

#### in1d(arr1，arr2)测试一维数组的每个元素是否存在于第二个数组中。

In [20]:
test = np.array([0, 1, 2, 5, 0])

In [21]:
states = [0, 2]

In [22]:
mask = np.in1d(test, states)
mask

array([ True, False,  True, False,  True])

In [23]:
test[mask]

array([0, 2, 0])

In [24]:
# invert参数如果为 True，则返回数组中的值被反转（即，如果 ar1 的元素在 ar2 中，则为 False，否则为 True）。默认为假。
mask = np.in1d(test, states, invert=True)
mask

array([False,  True, False,  True, False])

In [25]:
test[mask]

array([1, 5])

#### isin(element, test_elements)返回一个与 element 形状相同的布尔数组，如果 element 的元素在 test_elements 中，则为 True，否则为 False。

In [26]:
element = 2*np.arange(4).reshape((2, 2))
element

array([[0, 2],
       [4, 6]])

In [27]:
test_elements = [1, 2, 4, 8]

In [28]:
mask = np.isin(element, test_elements)
mask

array([[False,  True],
       [ True, False]])

In [29]:
element[mask]

array([2, 4])