In [1]:
import numpy as np

# 1.sort()方法：

##### ndarray的sort实例方法

In [2]:
arr = np.random.randn(3,4)
arr

array([[-1.00750391, -0.32094115, -0.03034299, -0.50093828],
       [ 0.38724458,  0.41708784,  0.72765547, -0.79893206],
       [-1.0404649 ,  0.72726869, -0.33227455, -0.51267791]])

In [3]:
arr.sort()

In [4]:
arr

array([[-1.00750391, -0.50093828, -0.32094115, -0.03034299],
       [-0.79893206,  0.38724458,  0.41708784,  0.72765547],
       [-1.0404649 , -0.51267791, -0.33227455,  0.72726869]])

#### 顶层的np.sort()方法

In [5]:
arr = np.random.randn(3,4)
arr

array([[ 0.51549219, -0.73507244, -0.74865696,  0.1459806 ],
       [-1.49291753,  0.58386771,  1.82306737,  0.37704324],
       [-0.79483826,  0.20976823,  1.16073258, -0.6924981 ]])

In [6]:
np.sort(arr)

array([[-0.74865696, -0.73507244,  0.1459806 ,  0.51549219],
       [-1.49291753,  0.37704324,  0.58386771,  1.82306737],
       [-0.79483826, -0.6924981 ,  0.20976823,  1.16073258]])

In [7]:
# 原数组未变化
arr

array([[ 0.51549219, -0.73507244, -0.74865696,  0.1459806 ],
       [-1.49291753,  0.58386771,  1.82306737,  0.37704324],
       [-0.79483826,  0.20976823,  1.16073258, -0.6924981 ]])

#### 使用axis参数，对指定轴进行排序

In [8]:
arr = np.random.randn(3,4)
arr

array([[ 0.02016259, -0.88519477,  0.18271565, -0.48720066],
       [ 1.13585177,  0.84505628,  0.66586759,  0.72760203],
       [-1.71443987, -0.33173916, -2.69395075,  0.49404124]])

In [9]:
arr.sort(axis=0)

In [10]:
arr

array([[-1.71443987, -0.88519477, -2.69395075, -0.48720066],
       [ 0.02016259, -0.33173916,  0.18271565,  0.49404124],
       [ 1.13585177,  0.84505628,  0.66586759,  0.72760203]])

# 2.间接排序：

#### argsort()——返回对数组进行排序的整数索引

In [11]:
arr = np.random.randn(4)
arr

array([ 0.23219428, -1.10602896, -0.19865998,  0.25639759])

In [12]:
indexer = arr.argsort()
indexer

array([1, 2, 0, 3], dtype=int64)

In [13]:
arr[indexer]

array([-1.10602896, -0.19865998,  0.23219428,  0.25639759])

#### lexsort()——使用多键数组执行间接稳定排序

In [48]:
first = np.array(['Bo', 'Ja', 'St', 'Bl', 'Ba'])
last = np.array(['Po', 'Ar', 'Ak', 'Po', 'Ta'])

In [49]:
sorter = np.lexsort((first , last))
sorter

array([2, 1, 3, 0, 4], dtype=int64)

In [50]:
list(zip(last[sorter], first[sorter]))

[('Ak', 'St'), ('Ar', 'Ja'), ('Po', 'Bl'), ('Po', 'Bo'), ('Ta', 'Ba')]

# 3.数组的部分排序：

#### np.partition()——返回结果中的前k个元素为最小的k个值

In [17]:
arr = np.array([-1,-2,-5,-9,-7,5,2,6])
arr

array([-1, -2, -5, -9, -7,  5,  2,  6])

In [18]:
np.partition(arr , 2)

array([-9, -7, -5, -1, -2,  5,  2,  6])

#### np.argpartition()——返回结果中的前k个元素为最小的k个值的索引值

In [19]:
indices = np.argpartition(arr,2)
indices

array([3, 4, 2, 0, 1, 5, 6, 7], dtype=int64)

In [20]:
arr[indices]

array([-9, -7, -5, -1, -2,  5,  2,  6])

In [21]:
arr.take(indices)

array([-9, -7, -5, -1, -2,  5,  2,  6])

# 4.在已排序的数组中寻找元素：

In [22]:
arr = np.array([0, 1, 5, 10, 15])

In [23]:
# 可以传递单个值
arr.searchsorted(9)

3

In [24]:
# 可以传递一个值数组
# 当传递的值与原数组中的值相同时，默认返回原数组相同值左侧的索引
arr.searchsorted([1,3,9,20])

array([1, 2, 3, 5], dtype=int64)

#### 作为该方法的一个小应用，可以用来分隔数据的单独的“桶边界”​数

In [25]:
bins = np.array([0,10,50,100])
bins

array([  0,  10,  50, 100])

In [26]:
data = np.random.uniform(0, 100, size=10)
data

array([ 9.83824212, 31.45365149, 54.74011411, 61.32103292, 97.61036597,
        4.43257959,  1.15463366, 93.37763642, 85.34062138, 71.21061072])

In [27]:
labels = bins.searchsorted(data)
labels

array([1, 2, 3, 3, 3, 1, 1, 3, 3, 3], dtype=int64)