In [1]:
import numpy as np

# 1.线性代数函数：

In [2]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [3]:
y = np.array([[6., 23.], [-1, 7], [8, 9]])
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [4]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [5]:
x@y

array([[ 28.,  64.],
       [ 67., 181.]])

# 2.文件读写

#### save()方法用于将数组存储到硬盘中

In [6]:
arr = np.arange(5)

In [7]:
np.save('test' , arr)

#### load()方法用于将数组从硬盘中载入

In [8]:
np.load('test.npy')

array([0, 1, 2, 3, 4])

#### savez()方法，可以用于保存多个数组

In [9]:
arr1 = np.arange(0,5)
arr2 = np.arange(5,10)

In [10]:
np.savez('test2.npz' , x=arr1 , y=arr2)

#### 当加载一个.npz文件时，会得到一个类似字典的对象

In [11]:
data = np.load('test2.npz')

In [12]:
data['x']

array([0, 1, 2, 3, 4])

In [13]:
data['y']

array([5, 6, 7, 8, 9])