In [1]:
import numpy as np

# 1.生成ndarray：

### 1.1 使用array函数生成ndarray：

In [2]:
np.array([1.1 , 2.2 , 3.3 , 4.4])

array([1.1, 2.2, 3.3, 4.4])

In [3]:
np.array([[1.1 , 2.2 , 3.3 , 4.4] , [5.5 , 6.6 , 7.7 , 8.8]])

array([[1.1, 2.2, 3.3, 4.4],
       [5.5, 6.6, 7.7, 8.8]])

In [4]:
np.array((1.1 , 2.2 , 3.3 , 4.4))

array([1.1, 2.2, 3.3, 4.4])

### 1.2 使用生成函数生成ndarray：

In [5]:
# np.asarray()——将输入转换为ndarray
np.asarray([1.1 , 2.2 , 3.3 , 4.4])

array([1.1, 2.2, 3.3, 4.4])

In [6]:
# np.asarray()——将输入转换为ndarray，但是如果输入已经是ndarray则不再复制
arr = np.array([5.5 , 6.6 , 7.7 , 8.8])
np.asarray(arr)

array([5.5, 6.6, 7.7, 8.8])

In [7]:
# np.arange(n)——类似range()函数，返回ndarray类型，元素从0到n-1
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# np.ones(shape)——根据shape生成一个全1数组，shape是元祖类型
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [9]:
# np.ones_like(a)——根据数组a的形状生成一个全1数组
arr = np.array([[[1.1 , 2.2] , [3.3 , 4.4]] , [[5.5 , 6.6] , [7.7 , 8.8]]])
arr

array([[[1.1, 2.2],
        [3.3, 4.4]],

       [[5.5, 6.6],
        [7.7, 8.8]]])

In [10]:
np.ones_like(arr)

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [11]:
# np.zeros(shape)——根据shape生成一个全0数组，shape是元祖类型
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
# np.zeros_like(a)——根据数组a的形状生成一个全0数组
arr = np.array([[[1.1 , 2.2] , [3.3 , 4.4]] , [[5.5 , 6.6] , [7.7 , 8.8]]])
np.zeros_like(arr)

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [13]:
# np.empty(shape)——根据shape生成一个没有初始化数值的空数组，shape是元祖类型
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
# np.empty_like(a)——根据数组a的形状生成一个没有初始化数值的空数组
arr = np.array([[[1.1 , 2.2] , [3.3 , 4.4]] , [[5.5 , 6.6] , [7.7 , 8.8]]])
np.empty_like(arr)

array([[[1.1, 2.2],
        [3.3, 4.4]],

       [[5.5, 6.6],
        [7.7, 8.8]]])

In [15]:
# np.full(shape,val)——根据shape生成一个数组，每个元素都是val
np.full((2,3) , 99)

array([[99, 99, 99],
       [99, 99, 99]])

In [16]:
# np.full_like(a,val)——根据数组a的形状生成一个数组，每个元素值都是val
arr = np.array([[[1.1 , 2.2] , [3.3 , 4.4]] , [[5.5 , 6.6] , [7.7 , 8.8]]])
np.full_like(arr , 99)

array([[[99., 99.],
        [99., 99.]],

       [[99., 99.],
        [99., 99.]]])

In [17]:
# np.eye(n)——创建一个正方的n×n单位矩阵，对角线为1，其余为0
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
# np.linspace(start, stop, num, endpoint, retstep, dtype)

# star和stop为起始和终止位置，均为标量
# num为包括start和stop的间隔点总数，默认为50
# endpoint为bool值，为False时将会去掉最后一个点计算间隔
# restep为bool值，为True时会同时返回数据列表和间隔值
# dtype默认为输入变量的类型，给定类型后将会把生成的数组类型转为目标类型
np.linspace(0,10 , num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# 2.ndarray对象的属性：

In [19]:
arr = np.array([[[1.1 , 2.2] , [3.3 , 4.4]] , [[5.5 , 6.6] , [7.7 , 8.8]]])
arr

array([[[1.1, 2.2],
        [3.3, 4.4]],

       [[5.5, 6.6],
        [7.7, 8.8]]])

In [20]:
# 轴的数量或维度的数量
arr.ndim

3

In [21]:
# ndarray对象尺度
arr.shape

(2, 2, 2)

In [22]:
# ndarray对象元素的个数
arr.size

8

In [23]:
# ndarray对象的元素类型
arr.dtype

dtype('float64')

In [24]:
# ndarray对象中每个元素的大小，以字节为单位
arr.itemsize

8