In [1]:
import numpy as np

# 1.ndarray对象的数据类型：

In [2]:
arr = np.array([[0,1,2,3,4],[9,8,7,6,5]])
arr

array([[0, 1, 2, 3, 4],
       [9, 8, 7, 6, 5]])

In [3]:
# 查看元素数据类型
arr.dtype

dtype('int32')

# 2.数据类型转换转换：

In [4]:
arr = np.array([[0,1,2,3,4],[9,8,7,6,5]])

In [5]:
arr.dtype

dtype('int32')

In [6]:
float_arr = arr.astype(np.float64)

In [7]:
float_arr

array([[0., 1., 2., 3., 4.],
       [9., 8., 7., 6., 5.]])

In [8]:
float_arr.dtype

dtype('float64')

#### 如果将浮点数转换为整数的话，那么原有数据小数点后的部分将会被消除

In [9]:
arr = np.array([1.23 , -2.34 , 3.45 , -4.56 , 5.67])
arr

array([ 1.23, -2.34,  3.45, -4.56,  5.67])

In [10]:
int_arr = arr.astype(np.int64)

In [11]:
int_arr

array([ 1, -2,  3, -4,  5], dtype=int64)

#### 将一个代表数字的字符串数组转换为数字形式

In [12]:
num_str_arr = np.array(['1.23' , '-2.34' , '3.45' , '-4.56' , '5.67'] ,  dtype=np.string_)

In [13]:
num_str_arr

array([b'1.23', b'-2.34', b'3.45', b'-4.56', b'5.67'], dtype='|S5')

In [14]:
num_arr = num_str_arr.astype(np.float64)

In [15]:
num_arr

array([ 1.23, -2.34,  3.45, -4.56,  5.67])

In [16]:
num_arr.dtype

dtype('float64')