In [1]:
import numpy as np

# 1.基础索引与切片：

### 1.1 基础索引：

#### 一维数组的索引：与python的列表类似

In [2]:
arr = np.array([9,8,7,6,5])
arr

array([9, 8, 7, 6, 5])

In [3]:
arr[2]

7

#### 多维数组的索引：每个维度一个索引值，以逗号分隔

In [4]:
# 二维数组
arr_2d = np.array([[9,8,7] , [6,5,4] , [3,2,1]])
arr_2d

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [5]:
# 查看数组的形状尺度
arr_2d.shape

(3, 3)

In [6]:
# 在第一个维度上获取第2个，在第二个维度上获取第3个
arr_2d[1,2]

4

In [7]:
# 单个元素的获取也可以通过递归的方式获得
arr_2d[1][2]

4

In [8]:
arr_2d[-1,-2] , arr_2d[-1][-2]

(2, 2)

In [9]:
# 三维数组
arr_3d = np.array([[[12,11,10] , [9,8,7]] , [[6,5,4] , [3,2,1]]])
arr_3d

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [10]:
arr_3d.shape

(2, 2, 3)

In [11]:
arr_3d[1,0,2]

4

In [12]:
arr_3d[1][0][2]

4

In [13]:
arr_3d[-1,-1,-2] , arr_3d[-1][-1][-2]

(2, 2)

### 1.2 基础切片：

#### 一维数组的索引：与python的列表类似

In [14]:
arr = np.array([9,8,7,6,5])
arr

array([9, 8, 7, 6, 5])

In [15]:
arr[1:4:2]

array([8, 6])

#### 多维数组的切片：

In [16]:
# 二维数组
arr_2d = np.array([[9,8,7] , [6,5,4] , [3,2,1]])
arr_2d

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [17]:
arr_2d.shape

(3, 3)

In [18]:
arr_2d[1: , :2]

array([[6, 5],
       [3, 2]])

In [19]:
arr_2d[1: , :2].shape

(2, 2)

In [20]:
# 三维数组
arr_3d = np.array([[[18,17,16] , [15,14,13] , [12,11,10]] , [[9,8,7] , [6,5,4] , [3,2,1]]])
arr_3d

array([[[18, 17, 16],
        [15, 14, 13],
        [12, 11, 10]],

       [[ 9,  8,  7],
        [ 6,  5,  4],
        [ 3,  2,  1]]])

In [21]:
arr_3d.shape

(2, 3, 3)

In [22]:
arr_3d[1: ,:2 ,2:]

array([[[7],
        [4]]])

In [23]:
arr_3d[1: ,:2 ,2:].shape

(1, 2, 1)

#### 如果将索引和切片混合使用，可以得到低维度的切片：

In [24]:
# 二维数组
arr_2d = np.array([[9,8,7] , [6,5,4] , [3,2,1]])
arr_2d

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [25]:
arr_2d.shape

(3, 3)

In [26]:
arr_2d[1: , 2]

array([4, 1])

In [27]:
arr_2d[1: , 2].shape

(2,)

In [28]:
# 三维数组
arr_3d = np.array([[[18,17,16] , [15,14,13] , [12,11,10]] , [[9,8,7] , [6,5,4] , [3,2,1]]])
arr_3d

array([[[18, 17, 16],
        [15, 14, 13],
        [12, 11, 10]],

       [[ 9,  8,  7],
        [ 6,  5,  4],
        [ 3,  2,  1]]])

In [29]:
arr_3d.shape

(2, 3, 3)

In [30]:
arr_3d[1: ,:2 ,2]

array([[7, 4]])

In [31]:
arr_3d[1: ,:2 ,2].shape

(1, 2)

#### 数组切片是原始数组的视图。这意味着数据不会被复制，对视图的任何修改都会反映在源数组上。

In [32]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr[::2]

array([0, 2, 4, 6, 8])

In [34]:
arr[::2] = 99

In [35]:
arr

array([99,  1, 99,  3, 99,  5, 99,  7, 99,  9])

# 2.布尔索引：

In [36]:
arr = np.array([[[18,17,-16] , [15,-14,13] , [12,-11,-10]] , [[9,-8,7] , [6,5,-4] , [3,-2,1]]])
arr

array([[[ 18,  17, -16],
        [ 15, -14,  13],
        [ 12, -11, -10]],

       [[  9,  -8,   7],
        [  6,   5,  -4],
        [  3,  -2,   1]]])

In [37]:
arr < 0

array([[[False, False,  True],
        [False,  True, False],
        [False,  True,  True]],

       [[False,  True, False],
        [False, False,  True],
        [False,  True, False]]])

In [38]:
arr[arr < 0]

array([-16, -14, -11, -10,  -8,  -4,  -2])

In [39]:
arr[arr < 0] = 0

In [40]:
arr

array([[[18, 17,  0],
        [15,  0, 13],
        [12,  0,  0]],

       [[ 9,  0,  7],
        [ 6,  5,  0],
        [ 3,  0,  1]]])

# 3.神奇索引：

In [41]:
arr = np.array([[18,17,16] , [15,14,13] , [12,11,10] , [9,8,7] , [6,5,4] , [3,2,1]])
arr

array([[18, 17, 16],
       [15, 14, 13],
       [12, 11, 10],
       [ 9,  8,  7],
       [ 6,  5,  4],
       [ 3,  2,  1]])

In [42]:
arr.shape

(6, 3)

In [43]:
# 传递一个包含指明所需顺序的列表或数组
arr[[0,2,4,5]]

array([[18, 17, 16],
       [12, 11, 10],
       [ 6,  5,  4],
       [ 3,  2,  1]])

In [44]:
# 传递一个包含指明所需顺序的列表或数组——负索引
arr[[-6,-4,-2,-1]]

array([[18, 17, 16],
       [12, 11, 10],
       [ 6,  5,  4],
       [ 3,  2,  1]])

In [45]:
# 传递多个数组
arr[[0,2,4,5] , [0,1,0,1]]

array([18, 11,  6,  2])

In [46]:
# 根据每个索引元祖对应的元素选出一个一维数组进行索引
arr[0,0] , arr[2,1] , arr[4,0] , arr[5,1]

(18, 11, 6, 2)