In [1]:
import numpy as np

# 1.数组算术：

In [2]:
arr1 = np.array([[1,2,3,4],[9,8,7,6]])
arr1

array([[1, 2, 3, 4],
       [9, 8, 7, 6]])

In [3]:
arr2 = np.array([[4,3,2,1],[6,7,8,9]])
arr2

array([[4, 3, 2, 1],
       [6, 7, 8, 9]])

In [4]:
arr1 + arr2

array([[ 5,  5,  5,  5],
       [15, 15, 15, 15]])

In [5]:
arr1 * arr2

array([[ 4,  6,  6,  4],
       [54, 56, 56, 54]])

In [6]:
1 / arr1

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.11111111, 0.125     , 0.14285714, 0.16666667]])

In [7]:
arr2 * 0.8

array([[3.2, 2.4, 1.6, 0.8],
       [4.8, 5.6, 6.4, 7.2]])

# 2.数组的变换：

#### ndarray数组的维度变换方法：

In [8]:
arr = np.array([[[12,11,10] , [9,8,7]] , [[6,5,4] , [3,2,1]]])
arr

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [9]:
arr.shape

(2, 2, 3)

In [10]:
# reshape(shape)——不改变数组元素，返回一个shape形状的数组，原数组不变
arr.reshape((2,6))

array([[12, 11, 10,  9,  8,  7],
       [ 6,  5,  4,  3,  2,  1]])

In [11]:
arr

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [12]:
# resize(shape)——与reshape()功能一致，但修改原数组
arr.resize((3,2,2))

In [13]:
arr

array([[[12, 11],
        [10,  9]],

       [[ 8,  7],
        [ 6,  5]],

       [[ 4,  3],
        [ 2,  1]]])

In [14]:
arr.shape

(3, 2, 2)

In [15]:
# swapaxes(ax1,ax2)——将数组n个维度中两个维度进行调换
arr.swapaxes(0,1)

array([[[12, 11],
        [ 8,  7],
        [ 4,  3]],

       [[10,  9],
        [ 6,  5],
        [ 2,  1]]])

In [16]:
arr.swapaxes(0,1).shape

(2, 3, 2)

In [17]:
# flatten()——对数组进行降维，返回折叠后的一维数组，原数组不变
arr.flatten()

array([12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [18]:
arr

array([[[12, 11],
        [10,  9]],

       [[ 8,  7],
        [ 6,  5]],

       [[ 4,  3],
        [ 2,  1]]])

#### ndarray数组向列表的转换：

In [19]:
arr = np.array([[1,2,3,4],[9,8,7,6]])
arr

array([[1, 2, 3, 4],
       [9, 8, 7, 6]])

In [20]:
arr.tolist()

[[1, 2, 3, 4], [9, 8, 7, 6]]

# 3.数组转置与换轴：

#### 数组拥有transpose方法，也有特殊的T属性。

In [21]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [22]:
arr.transpose

<function ndarray.transpose>

In [23]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [24]:
arr.T.shape

(5, 3)

#### 对于更高纬度的数组，transpose方法可以接受包含轴编号的元组，用于转置轴。

In [25]:
arr = np.arange(24).reshape((2,3,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [26]:
# 下面的操作是将原来的第三个轴变为第一个，原来的第一个轴变为第二个轴，原来的第二个轴变为第三个轴
arr.transpose((2,0,1))

array([[[ 0,  4,  8],
        [12, 16, 20]],

       [[ 1,  5,  9],
        [13, 17, 21]],

       [[ 2,  6, 10],
        [14, 18, 22]],

       [[ 3,  7, 11],
        [15, 19, 23]]])

In [27]:
arr.transpose((2,0,1)).shape

(4, 2, 3)

In [28]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [29]:
arr.T

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [30]:
arr.T.shape

(4, 3, 2)