In [1]:
import numpy as np
import pandas as pd

# 1.to_numpy 方法：

### 要把一个DataFrame变成一个NumPy数组，需要使用to_numpy方法。

In [2]:
data = pd.DataFrame({'x': [1, 2, 3, 4, 5],'y': [6, 7, 8, 9, 10],'z': [11, 12, 13, 14, 15]})
data

x   y   z
0  1   6  11
1  2   7  12
2  3   8  13
3  4   9  14
4  5  10  15

In [3]:
data.columns

Index(['x', 'y', 'z'], dtype='object')

In [4]:
data.to_numpy()

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]], dtype=int64)

### 要将一个数组转换回 DataFrame，你可能还记得前面的章节中的内容，你可以传递一个含有列名的二维ndarray。

In [5]:
data2 = pd.DataFrame(data.to_numpy(), columns=['one', 'two', 'three'])
data2

one  two  three
0    1    6     11
1    2    7     12
2    3    8     13
3    4    9     14
4    5   10     15

### to_numpy 方法一般在数据是同质化的时候使用，例如，均为数字类型。如果数据为异质性的，结果将是一个Python对象的ndarray。

In [6]:
data3 = data.copy()
data3['strings'] = ['a', 'b', 'c', 'd', 'e']
data3

x   y   z strings
0  1   6  11       a
1  2   7  12       b
2  3   8  13       c
3  4   9  14       d
4  5  10  15       e

In [7]:
data3.to_numpy()

array([[1, 6, 11, 'a'],
       [2, 7, 12, 'b'],
       [3, 8, 13, 'c'],
       [4, 9, 14, 'd'],
       [5, 10, 15, 'e']], dtype=object)

### 对于某些模型，你可能希望只使用一部分列，此时推荐 to_numpy 和 loc 索引一起使用。

In [8]:
model_cols = ['x', 'y']

In [9]:
data.loc[:, model_cols].to_numpy()

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]], dtype=int64)

# 2.Categorical 类型和pandas.get_dummies函数：

### 假设在下面的示例数据中有一个非数字类型的列，如果我们想用虚拟变量替换 "category "列，我们首先需要创建虚拟变量，然后删除 "category "列，最后连接结果。

In [10]:
data['category'] = pd.Categorical(['a', 'b', 'a', 'b', 'a'],categories=['a', 'b'])
data

x   y   z category
0  1   6  11        a
1  2   7  12        b
2  3   8  13        a
3  4   9  14        b
4  5  10  15        a

In [11]:
# 创建虚拟变量
dummies = pd.get_dummies(data.category, prefix='category')
dummies

category_a  category_b
0           1           0
1           0           1
2           1           0
3           0           1
4           1           0

In [12]:
# 删除 "category "列，然后连接结果
data_with_dummies = data.drop('category', axis=1).join(dummies)
data_with_dummies

x   y   z  category_a  category_b
0  1   6  11           1           0
1  2   7  12           0           1
2  3   8  13           1           0
3  4   9  14           0           1
4  5  10  15           1           0

In [13]:
# pd.concat([data.drop('category', axis=1) , dummies],axis=1)