In [1]:
import numpy as np

from random import normalvariate

# 1.numpy.random模块

#### numpy.random模块相比python内置random模块更高效

In [2]:
%timeit [normalvariate(0,1) for _ in range(1_000_000)]

899 ms ± 39 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [3]:
%timeit np.random.standard_normal(size=1_000_000)

28.3 ms ± 1.19 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


# 2.随机数生成器（Random Number Generator）

In [4]:
rng = np.random.default_rng(seed=123)

rng.standard_normal(size=3)

array([-0.98912135, -0.36778665,  1.28792526])

# 3.随机数生成函数：

#### permutation()——返回一个序列的随机排列，或者返回一个乱序的整数范围序列

In [5]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
np.random.permutation(np.arange(10))

array([0, 9, 2, 6, 7, 1, 3, 4, 8, 5])

In [7]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### shuffle()——随机排列一个序列

In [8]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
np.random.shuffle(arr)

In [10]:
arr

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3]])

#### rand()——服从[0,1)均匀分布的随机样本值

In [11]:
np.random.rand(2,3,4)

array([[[0.12453376, 0.587713  , 0.59353242, 0.68696834],
        [0.26134011, 0.90174625, 0.0602396 , 0.69735556],
        [0.95849126, 0.39550943, 0.04836672, 0.82208411]],

       [[0.79226768, 0.04989878, 0.94357896, 0.38639065],
        [0.35406239, 0.38787451, 0.91429871, 0.32593029],
        [0.5629369 , 0.81546556, 0.02370342, 0.96933346]]])

#### randint(low，high，size，dtype)——根据给定值，从低到高抽取随机整数

In [12]:
np.random.randint(low=1,high=100,size=(2,3) , dtype=np.uint8)

array([[ 6, 16, 18],
       [93, 46, 90]], dtype=uint8)

#### randn()——从均值为0方差为1的正态分布中抽取样本

In [13]:
np.random.randn(2,3)

array([[-2.08932259, -2.02220746, -1.55247689],
       [-1.1040037 , -1.55304768, -0.50908448]])

#### normal(loc,scale,size)——从正态高斯分布中抽取样本

In [14]:
# 参数loc：正态分布的均值，对应着这个分布的中心。loc=0说明这一个以Y轴为对称轴的正态分布，
# 参数scale：正态分布的标准差，对应分布的宽度，scale越大，正态分布的曲线越矮胖，scale越小，曲线越高瘦。
# 参数size：输出的值赋在shape里，默认为None。

In [15]:
np.random.normal(loc=1,scale=10,size=(2,3))

array([[-6.06039553, -1.30168895,  5.01405663],
       [ 5.21707312, -2.76304848,  7.58415285]])

#### uniform(low,high,size)——从均匀[low,high)分布总抽取样本

In [16]:
np.random.uniform(low=1,high=5,size=(2,3))

array([[2.05445572, 1.81120029, 1.17701333],
       [3.6072588 , 3.65197264, 2.55620417]])

#### binomial(n,p,size)——从二项分布中抽取样本

In [17]:
# 参数n：一次试验的样本数n，并且相互不干扰。
# 参数p：事件发生的概率p，范围[0,1]。
# 参数size：限定了返回值的形式

In [18]:
np.random.binomial(n=20 ,p=0.5 , size=(2,3))

array([[16, 10, 10],
       [ 9, 10, 15]])

#### beta(a,b,size)——从beta分布中抽取样本

In [19]:
np.random.beta(10,20,(2,3))

array([[0.29955353, 0.27305211, 0.29631743],
       [0.24527276, 0.39024413, 0.32837931]])

#### chisquare(df,size)——从卡方分布中抽取样本

In [20]:
np.random.chisquare(df=2, size=(2, 3))

array([[1.98222902, 3.0758696 , 0.51192377],
       [0.3869275 , 0.76172903, 2.51366813]])

#### gamma(shape, scale, size)——从伽马分布中抽取样本

In [21]:
np.random.gamma(shape=3,scale=20,size=(2,3))

array([[ 49.1124033 ,  57.9164554 ,  52.17023793],
       [147.00978216, 192.88657351,  42.82605707]])