In [1]:
import numpy as np

# 一元函数：对ndarray中的数据执行元素级运算的函数

In [2]:
arr = np.arange(-3,3).reshape(2,3) * 2.3
arr

array([[-6.9, -4.6, -2.3],
       [ 0. ,  2.3,  4.6]])

In [3]:
# 计算数组各元素的平方
np.square(arr)

array([[47.61, 21.16,  5.29],
       [ 0.  ,  5.29, 21.16]])

In [4]:
# 计算数组各元素的符号值
np.sign(arr)

array([[-1., -1., -1.],
       [ 0.,  1.,  1.]])

In [5]:
# 计算数组各元素的ceiling值
# 即大于或等于该数字的最小整数——向上取整
np.ceil(arr)

array([[-6., -4., -2.],
       [ 0.,  3.,  5.]])

In [6]:
# 计算数组各元素的floor值
# 即小于或等于每个元素的最大整数——向下取整
np.floor(arr)

array([[-7., -5., -3.],
       [ 0.,  2.,  4.]])

In [7]:
# 计算数组各元素的四舍五入值
np.rint(arr)

array([[-7., -5., -2.],
       [ 0.,  2.,  5.]])

In [8]:
# 计算数组各元素的小数和整数部分
# 以两个独立数组形式返回
np.modf(arr)

(array([[-0.9, -0.6, -0.3],
        [ 0. ,  0.3,  0.6]]),
 array([[-6., -4., -2.],
        [ 0.,  2.,  4.]]))

In [9]:
# 逻辑非
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [10]:
np.logical_not(x<3)

array([False, False, False,  True,  True])

# 二元函数：接收两个数组并返回一个数组作为结果

In [11]:
arr1 = np.random.randint(-20 , 20 , (2,3))
arr1

array([[ -5,  -1,  -3],
       [-18, -15,   1]])

In [12]:
arr2 = np.random.randint(-20 , 20 , (2,3))
arr2

array([[  5,   1, -11],
       [-18,  16, -19]])

In [13]:
# 加法
np.add(arr1 , arr2)

array([[  0,   0, -14],
       [-36,   1, -18]])

In [14]:
# 除法
np.divide(arr1,arr2)

array([[-1.        , -1.        ,  0.27272727],
       [ 1.        , -0.9375    , -0.05263158]])

In [15]:
# 整除运算
np.floor_divide(arr1,arr2)

array([[-1, -1,  0],
       [ 1, -1, -1]], dtype=int32)

In [16]:
# 元素级的最大值计算
np.maximum(arr1,arr2)

array([[  5,   1,  -3],
       [-18,  16,   1]])

In [17]:
# copysign(x,y)将数组y中各元素的符号赋值给数组x对应元素
np.copysign(arr1,arr2)

array([[  5.,   1.,  -3.],
       [-18.,  15.,  -1.]])

In [18]:
# 算术比较，与数学操作符（> < >= <= == !=）效果一致
np.greater(arr1,arr2)

array([[False, False,  True],
       [False, False,  True]])

In [19]:
arr1 > arr2

array([[False, False,  True],
       [False, False,  True]])

In [20]:
# 逻辑与，逻辑或，逻辑异或
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [21]:
np.logical_and(x>1, x<4)

array([False, False,  True,  True, False])

In [22]:
np.logical_or(x>1, x<4)

array([ True,  True,  True,  True,  True])

In [23]:
np.logical_xor(x>1, x<4)

array([ True,  True, False, False,  True])